theme: jekyll-theme-cayman
title: Memory and Ideology in the Linguistic Landscape
description: Commemorative (re)naming in East Germany and Poland 1916-2018
image: http://mill.wa.amu.edu.pl/sites/default/files/G_Fabiszak_baner_ulice_b.jpg
banner: http://mill.wa.amu.edu.pl/sites/default/files/G_Fabiszak_baner_ulice_b.jpg
