theme: jekyll-theme-cayman
title: Commemorative (re)naming in East Germany and Poland 1916-2018
description: TEST
image: http://mill.wa.amu.edu.pl/sites/default/files/G_Fabiszak_baner_ulice_b.jpg
banner: http://mill.wa.amu.edu.pl/sites/default/files/G_Fabiszak_baner_ulice_b.jpg
